# Using the official Python Docker image as default
image: python

# Columns of the pipeline
stages:
  - static analysis
  - build
  - test

# Static code analysis job via Pylint
static analysis:
  stage: static analysis
  before_script:
    - pip install pylint
  script:
    - pylint test.py
  allow_failure: true

# Compilation job
build:
  stage: build
  script:
    - pip install .

# Unit testing via PyTest
unit tests:
  stage: test
  before_script:
    - pip install pytest
  script:
    - py.test tests.py

